[platformio]
default_envs = esp32c3_esp32c3_ble

[env:esp32c3_rp2040_usbhid]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_flags =
  -D CONTROLLER_MODE_USB_HID
build_src_filter = -<*> +<main.cpp>
lib_deps =
  adafruit/Adafruit TinyUSB Library @ ^3.4.5

[env:esp32c3_esp32c3_ble]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -include Arduino.h
  -D CONTROLLER_MODE_BLE
  -D ESP32C3_STATUS_OLED
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<main.cpp>
lib_deps =
  lemmingdev/ESP32-BLE-Gamepad @ ^0.6.4
  olikraus/U8g2 @ ^2.36.4

[env:esp32c3_ble_mcp]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -include Arduino.h
  -D CONTROLLER_MODE_BLE
  -D ESP32C3_STATUS_OLED
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D USE_MCP23017_EXPANDER
build_src_filter = -<*> +<main.cpp>
lib_deps =
  lemmingdev/ESP32-BLE-Gamepad @ ^0.6.4
  olikraus/U8g2 @ ^2.36.4

[env:esp32c3_esp32c3_usbserial]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -D CONTROLLER_MODE_USB_SERIAL
  -D ESP32C3_STATUS_OLED
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<main.cpp>
lib_deps =
  olikraus/U8g2 @ ^2.36.4
