[platformio]
default_envs = cyberbrick_esp32c3_ble

[env:cyberbrick_rp2040_usbhid]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_flags =
  -D CONTROLLER_MODE_USB_HID
build_src_filter = -<*> +<main.cpp>
lib_deps =
  adafruit/Adafruit TinyUSB Library @ ^3.4.5

[env:cyberbrick_esp32c3_ble]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -include Arduino.h
  -D CONTROLLER_MODE_BLE
  -D CYBERBRICK_STATUS_OLED
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<main.cpp>
lib_deps =
  lemmingdev/ESP32-BLE-Gamepad @ ^0.6.4
  olikraus/U8g2 @ ^2.36.4

[env:cyberbrick_esp32c3_usbserial]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -D CONTROLLER_MODE_USB_SERIAL
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<main.cpp>

[env:cyberbrick_d1_dongle]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<d1_espnow_dongle.cpp>
